// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/ved.proto

package com.opentok.udfs;

public final class Ved {
  private Ved() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VedMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 link_index = 1;
    boolean hasLinkIndex();
    long getLinkIndex();
    
    // optional .com.opentok.udfs.VedMessage.Type link_type = 2;
    boolean hasLinkType();
    com.opentok.udfs.Ved.VedMessage.Type getLinkType();
    
    // optional uint64 sub_result_position = 5;
    boolean hasSubResultPosition();
    long getSubResultPosition();
    
    // optional uint64 result_position = 6;
    boolean hasResultPosition();
    long getResultPosition();
    
    // optional uint64 start_result_position = 7;
    boolean hasStartResultPosition();
    long getStartResultPosition();
    
    // optional uint64 v3 = 3;
    boolean hasV3();
    long getV3();
    
    // optional uint64 v4 = 4;
    boolean hasV4();
    long getV4();
    
    // optional uint64 v8 = 8;
    boolean hasV8();
    long getV8();
    
    // optional uint64 v9 = 9;
    boolean hasV9();
    long getV9();
    
    // optional uint64 v10 = 10;
    boolean hasV10();
    long getV10();
    
    // optional uint64 v11 = 11;
    boolean hasV11();
    long getV11();
    
    // optional uint64 v12 = 12;
    boolean hasV12();
    long getV12();
    
    // optional .com.opentok.udfs.VedMessage.Mysterious mysterious_msg = 13;
    boolean hasMysteriousMsg();
    com.opentok.udfs.Ved.VedMessage.Mysterious getMysteriousMsg();
    com.opentok.udfs.Ved.VedMessage.MysteriousOrBuilder getMysteriousMsgOrBuilder();
  }
  public static final class VedMessage extends
      com.google.protobuf.GeneratedMessage
      implements VedMessageOrBuilder {
    // Use VedMessage.newBuilder() to construct.
    private VedMessage(Builder builder) {
      super(builder);
    }
    private VedMessage(boolean noInit) {}
    
    private static final VedMessage defaultInstance;
    public static VedMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public VedMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      normal_universal_search_result(0, 22),
      blog_search_result(1, 152),
      patent_result(2, 232),
      patent_result_thumbnail(3, 235),
      image_search_result_in_basic_image_search_universal_search(4, 245),
      local_search_result(5, 288),
      news_result_thumbnail(6, 295),
      news_result(7, 297),
      more_results_link_listed_mainly_for_QA_websites(8, 300),
      video_result(9, 311),
      video_result_thumbnail(10, 312),
      oneline_sitelink(11, 338),
      shopping_search_result(12, 371),
      image_search_result(13, 429),
      new_image_search_result(14, 51),
      Jump_to_link(15, 586),
      map_search_result_website_link(16, 612),
      map_search_result_thumbnail(17, 646),
      adword_sitelink(18, 706),
      breadcrumb(19, 745),
      patent_result_Overview_Related_Discuss_link(20, 1107),
      book_search_result_author_link(21, 1140),
      normal_result_thumbnail_1(22, 1146),
      normal_result_thumbnail_2(23, 1150),
      local_search_result_marker_pin_icon(24, 1455),
      news_sub_result(25, 1532),
      sponsored_search_result(26, 1617),
      map_search_result(27, 1701),
      knowledge_graph_repeated_sub_link(28, 1732),
      sponsored_shopping_result_thumbnail(29, 1907),
      sponsored_shopping_result(30, 1908),
      sponsored_shopping_result_thumbnail_(31, 1986),
      sponsored_shopping_result_main_column_of_universal_search(32, 1987),
      sitelink(33, 2060),
      news_result_video_thumbnail(34, 2237),
      knowledge_graph_link(35, 2459),
      authorship_by_author_link(36, 2847),
      authorship_thumbnail_link(37, 2937),
      image_search_result_thumbnail(38, 3588),
      image_search_result_preview_View_image_link(39, 3596),
      image_search_result_preview_thumbnail(40, 3597),
      image_search_result_preview_title_link(41, 3598),
      image_search_result_preview_Visit_page_link(42, 3599),
      image_search_result_preview_grey_website_link_underneath_title(43, 3724),
      knowledge_graph_main_image(44, 3836),
      indepth_article_result(45, 5077),
      indepth_article_result_thumbnail(46, 5078),
      adword_oneline_sitelink(47, 5158),
      dictionary_definition_link(48, 5497),
      ;
      
      public static final int normal_universal_search_result_VALUE = 22;
      public static final int blog_search_result_VALUE = 152;
      public static final int patent_result_VALUE = 232;
      public static final int patent_result_thumbnail_VALUE = 235;
      public static final int image_search_result_in_basic_image_search_universal_search_VALUE = 245;
      public static final int local_search_result_VALUE = 288;
      public static final int news_result_thumbnail_VALUE = 295;
      public static final int news_result_VALUE = 297;
      public static final int more_results_link_listed_mainly_for_QA_websites_VALUE = 300;
      public static final int video_result_VALUE = 311;
      public static final int video_result_thumbnail_VALUE = 312;
      public static final int oneline_sitelink_VALUE = 338;
      public static final int shopping_search_result_VALUE = 371;
      public static final int image_search_result_VALUE = 429;
      public static final int new_image_search_result_VALUE = 51;
      public static final int Jump_to_link_VALUE = 586;
      public static final int map_search_result_website_link_VALUE = 612;
      public static final int map_search_result_thumbnail_VALUE = 646;
      public static final int adword_sitelink_VALUE = 706;
      public static final int breadcrumb_VALUE = 745;
      public static final int patent_result_Overview_Related_Discuss_link_VALUE = 1107;
      public static final int book_search_result_author_link_VALUE = 1140;
      public static final int normal_result_thumbnail_1_VALUE = 1146;
      public static final int normal_result_thumbnail_2_VALUE = 1150;
      public static final int local_search_result_marker_pin_icon_VALUE = 1455;
      public static final int news_sub_result_VALUE = 1532;
      public static final int sponsored_search_result_VALUE = 1617;
      public static final int map_search_result_VALUE = 1701;
      public static final int knowledge_graph_repeated_sub_link_VALUE = 1732;
      public static final int sponsored_shopping_result_thumbnail_VALUE = 1907;
      public static final int sponsored_shopping_result_VALUE = 1908;
      public static final int sponsored_shopping_result_thumbnail__VALUE = 1986;
      public static final int sponsored_shopping_result_main_column_of_universal_search_VALUE = 1987;
      public static final int sitelink_VALUE = 2060;
      public static final int news_result_video_thumbnail_VALUE = 2237;
      public static final int knowledge_graph_link_VALUE = 2459;
      public static final int authorship_by_author_link_VALUE = 2847;
      public static final int authorship_thumbnail_link_VALUE = 2937;
      public static final int image_search_result_thumbnail_VALUE = 3588;
      public static final int image_search_result_preview_View_image_link_VALUE = 3596;
      public static final int image_search_result_preview_thumbnail_VALUE = 3597;
      public static final int image_search_result_preview_title_link_VALUE = 3598;
      public static final int image_search_result_preview_Visit_page_link_VALUE = 3599;
      public static final int image_search_result_preview_grey_website_link_underneath_title_VALUE = 3724;
      public static final int knowledge_graph_main_image_VALUE = 3836;
      public static final int indepth_article_result_VALUE = 5077;
      public static final int indepth_article_result_thumbnail_VALUE = 5078;
      public static final int adword_oneline_sitelink_VALUE = 5158;
      public static final int dictionary_definition_link_VALUE = 5497;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 22: return normal_universal_search_result;
          case 152: return blog_search_result;
          case 232: return patent_result;
          case 235: return patent_result_thumbnail;
          case 245: return image_search_result_in_basic_image_search_universal_search;
          case 288: return local_search_result;
          case 295: return news_result_thumbnail;
          case 297: return news_result;
          case 300: return more_results_link_listed_mainly_for_QA_websites;
          case 311: return video_result;
          case 312: return video_result_thumbnail;
          case 338: return oneline_sitelink;
          case 371: return shopping_search_result;
          case 429: return image_search_result;
          case 51: return new_image_search_result;
          case 586: return Jump_to_link;
          case 612: return map_search_result_website_link;
          case 646: return map_search_result_thumbnail;
          case 706: return adword_sitelink;
          case 745: return breadcrumb;
          case 1107: return patent_result_Overview_Related_Discuss_link;
          case 1140: return book_search_result_author_link;
          case 1146: return normal_result_thumbnail_1;
          case 1150: return normal_result_thumbnail_2;
          case 1455: return local_search_result_marker_pin_icon;
          case 1532: return news_sub_result;
          case 1617: return sponsored_search_result;
          case 1701: return map_search_result;
          case 1732: return knowledge_graph_repeated_sub_link;
          case 1907: return sponsored_shopping_result_thumbnail;
          case 1908: return sponsored_shopping_result;
          case 1986: return sponsored_shopping_result_thumbnail_;
          case 1987: return sponsored_shopping_result_main_column_of_universal_search;
          case 2060: return sitelink;
          case 2237: return news_result_video_thumbnail;
          case 2459: return knowledge_graph_link;
          case 2847: return authorship_by_author_link;
          case 2937: return authorship_thumbnail_link;
          case 3588: return image_search_result_thumbnail;
          case 3596: return image_search_result_preview_View_image_link;
          case 3597: return image_search_result_preview_thumbnail;
          case 3598: return image_search_result_preview_title_link;
          case 3599: return image_search_result_preview_Visit_page_link;
          case 3724: return image_search_result_preview_grey_website_link_underneath_title;
          case 3836: return knowledge_graph_main_image;
          case 5077: return indepth_article_result;
          case 5078: return indepth_article_result_thumbnail;
          case 5158: return adword_oneline_sitelink;
          case 5497: return dictionary_definition_link;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.opentok.udfs.Ved.VedMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        normal_universal_search_result, blog_search_result, patent_result, patent_result_thumbnail, image_search_result_in_basic_image_search_universal_search, local_search_result, news_result_thumbnail, news_result, more_results_link_listed_mainly_for_QA_websites, video_result, video_result_thumbnail, oneline_sitelink, shopping_search_result, image_search_result, new_image_search_result, Jump_to_link, map_search_result_website_link, map_search_result_thumbnail, adword_sitelink, breadcrumb, patent_result_Overview_Related_Discuss_link, book_search_result_author_link, normal_result_thumbnail_1, normal_result_thumbnail_2, local_search_result_marker_pin_icon, news_sub_result, sponsored_search_result, map_search_result, knowledge_graph_repeated_sub_link, sponsored_shopping_result_thumbnail, sponsored_shopping_result, sponsored_shopping_result_thumbnail_, sponsored_shopping_result_main_column_of_universal_search, sitelink, news_result_video_thumbnail, knowledge_graph_link, authorship_by_author_link, authorship_thumbnail_link, image_search_result_thumbnail, image_search_result_preview_View_image_link, image_search_result_preview_thumbnail, image_search_result_preview_title_link, image_search_result_preview_Visit_page_link, image_search_result_preview_grey_website_link_underneath_title, knowledge_graph_main_image, indepth_article_result, indepth_article_result_thumbnail, adword_oneline_sitelink, dictionary_definition_link, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:com.opentok.udfs.VedMessage.Type)
    }
    
    public interface MysteriousOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional .com.opentok.udfs.VedMessage.Mysterious.NestedMysterious nested_mysterious_msg = 1;
      boolean hasNestedMysteriousMsg();
      com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious getNestedMysteriousMsg();
      com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysteriousOrBuilder getNestedMysteriousMsgOrBuilder();
    }
    public static final class Mysterious extends
        com.google.protobuf.GeneratedMessage
        implements MysteriousOrBuilder {
      // Use Mysterious.newBuilder() to construct.
      private Mysterious(Builder builder) {
        super(builder);
      }
      private Mysterious(boolean noInit) {}
      
      private static final Mysterious defaultInstance;
      public static Mysterious getDefaultInstance() {
        return defaultInstance;
      }
      
      public Mysterious getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_fieldAccessorTable;
      }
      
      public interface NestedMysteriousOrBuilder
          extends com.google.protobuf.MessageOrBuilder {
        
        // optional int64 ts = 1;
        boolean hasTs();
        long getTs();
        
        // optional sfixed32 mysterious1 = 2;
        boolean hasMysterious1();
        int getMysterious1();
        
        // optional sfixed32 mysterious2 = 3;
        boolean hasMysterious2();
        int getMysterious2();
      }
      public static final class NestedMysterious extends
          com.google.protobuf.GeneratedMessage
          implements NestedMysteriousOrBuilder {
        // Use NestedMysterious.newBuilder() to construct.
        private NestedMysterious(Builder builder) {
          super(builder);
        }
        private NestedMysterious(boolean noInit) {}
        
        private static final NestedMysterious defaultInstance;
        public static NestedMysterious getDefaultInstance() {
          return defaultInstance;
        }
        
        public NestedMysterious getDefaultInstanceForType() {
          return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_fieldAccessorTable;
        }
        
        private int bitField0_;
        // optional int64 ts = 1;
        public static final int TS_FIELD_NUMBER = 1;
        private long ts_;
        public boolean hasTs() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public long getTs() {
          return ts_;
        }
        
        // optional sfixed32 mysterious1 = 2;
        public static final int MYSTERIOUS1_FIELD_NUMBER = 2;
        private int mysterious1_;
        public boolean hasMysterious1() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getMysterious1() {
          return mysterious1_;
        }
        
        // optional sfixed32 mysterious2 = 3;
        public static final int MYSTERIOUS2_FIELD_NUMBER = 3;
        private int mysterious2_;
        public boolean hasMysterious2() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getMysterious2() {
          return mysterious2_;
        }
        
        private void initFields() {
          ts_ = 0L;
          mysterious1_ = 0;
          mysterious2_ = 0;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;
          
          memoizedIsInitialized = 1;
          return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeInt64(1, ts_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            output.writeSFixed32(2, mysterious1_);
          }
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            output.writeSFixed32(3, mysterious2_);
          }
          getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
        
          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(1, ts_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.CodedOutputStream
              .computeSFixed32Size(2, mysterious1_);
          }
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            size += com.google.protobuf.CodedOutputStream
              .computeSFixed32Size(3, mysterious2_);
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }
        
        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
          return super.writeReplace();
        }
        
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        
        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }
        
        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysteriousOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_descriptor;
          }
          
          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_fieldAccessorTable;
          }
          
          // Construct using com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }
          
          private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }
          
          public Builder clear() {
            super.clear();
            ts_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000001);
            mysterious1_ = 0;
            bitField0_ = (bitField0_ & ~0x00000002);
            mysterious2_ = 0;
            bitField0_ = (bitField0_ & ~0x00000004);
            return this;
          }
          
          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }
          
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDescriptor();
          }
          
          public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious getDefaultInstanceForType() {
            return com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDefaultInstance();
          }
          
          public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious build() {
            com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }
          
          private com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious buildParsed()
              throws com.google.protobuf.InvalidProtocolBufferException {
            com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(
                result).asInvalidProtocolBufferException();
            }
            return result;
          }
          
          public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious buildPartial() {
            com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious result = new com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.ts_ = ts_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.mysterious1_ = mysterious1_;
            if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
              to_bitField0_ |= 0x00000004;
            }
            result.mysterious2_ = mysterious2_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }
          
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious) {
              return mergeFrom((com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }
          
          public Builder mergeFrom(com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious other) {
            if (other == com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDefaultInstance()) return this;
            if (other.hasTs()) {
              setTs(other.getTs());
            }
            if (other.hasMysterious1()) {
              setMysterious1(other.getMysterious1());
            }
            if (other.hasMysterious2()) {
              setMysterious2(other.getMysterious2());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }
          
          public final boolean isInitialized() {
            return true;
          }
          
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder(
                this.getUnknownFields());
            while (true) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    this.setUnknownFields(unknownFields.build());
                    onChanged();
                    return this;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  ts_ = input.readInt64();
                  break;
                }
                case 21: {
                  bitField0_ |= 0x00000002;
                  mysterious1_ = input.readSFixed32();
                  break;
                }
                case 29: {
                  bitField0_ |= 0x00000004;
                  mysterious2_ = input.readSFixed32();
                  break;
                }
              }
            }
          }
          
          private int bitField0_;
          
          // optional int64 ts = 1;
          private long ts_ ;
          public boolean hasTs() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          public long getTs() {
            return ts_;
          }
          public Builder setTs(long value) {
            bitField0_ |= 0x00000001;
            ts_ = value;
            onChanged();
            return this;
          }
          public Builder clearTs() {
            bitField0_ = (bitField0_ & ~0x00000001);
            ts_ = 0L;
            onChanged();
            return this;
          }
          
          // optional sfixed32 mysterious1 = 2;
          private int mysterious1_ ;
          public boolean hasMysterious1() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          public int getMysterious1() {
            return mysterious1_;
          }
          public Builder setMysterious1(int value) {
            bitField0_ |= 0x00000002;
            mysterious1_ = value;
            onChanged();
            return this;
          }
          public Builder clearMysterious1() {
            bitField0_ = (bitField0_ & ~0x00000002);
            mysterious1_ = 0;
            onChanged();
            return this;
          }
          
          // optional sfixed32 mysterious2 = 3;
          private int mysterious2_ ;
          public boolean hasMysterious2() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
          }
          public int getMysterious2() {
            return mysterious2_;
          }
          public Builder setMysterious2(int value) {
            bitField0_ |= 0x00000004;
            mysterious2_ = value;
            onChanged();
            return this;
          }
          public Builder clearMysterious2() {
            bitField0_ = (bitField0_ & ~0x00000004);
            mysterious2_ = 0;
            onChanged();
            return this;
          }
          
          // @@protoc_insertion_point(builder_scope:com.opentok.udfs.VedMessage.Mysterious.NestedMysterious)
        }
        
        static {
          defaultInstance = new NestedMysterious(true);
          defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:com.opentok.udfs.VedMessage.Mysterious.NestedMysterious)
      }
      
      private int bitField0_;
      // optional .com.opentok.udfs.VedMessage.Mysterious.NestedMysterious nested_mysterious_msg = 1;
      public static final int NESTED_MYSTERIOUS_MSG_FIELD_NUMBER = 1;
      private com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious nestedMysteriousMsg_;
      public boolean hasNestedMysteriousMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious getNestedMysteriousMsg() {
        return nestedMysteriousMsg_;
      }
      public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysteriousOrBuilder getNestedMysteriousMsgOrBuilder() {
        return nestedMysteriousMsg_;
      }
      
      private void initFields() {
        nestedMysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, nestedMysteriousMsg_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, nestedMysteriousMsg_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.opentok.udfs.Ved.VedMessage.Mysterious parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.opentok.udfs.Ved.VedMessage.Mysterious prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.opentok.udfs.Ved.VedMessage.MysteriousOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_Mysterious_fieldAccessorTable;
        }
        
        // Construct using com.opentok.udfs.Ved.VedMessage.Mysterious.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getNestedMysteriousMsgFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (nestedMysteriousMsgBuilder_ == null) {
            nestedMysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDefaultInstance();
          } else {
            nestedMysteriousMsgBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.opentok.udfs.Ved.VedMessage.Mysterious.getDescriptor();
        }
        
        public com.opentok.udfs.Ved.VedMessage.Mysterious getDefaultInstanceForType() {
          return com.opentok.udfs.Ved.VedMessage.Mysterious.getDefaultInstance();
        }
        
        public com.opentok.udfs.Ved.VedMessage.Mysterious build() {
          com.opentok.udfs.Ved.VedMessage.Mysterious result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.opentok.udfs.Ved.VedMessage.Mysterious buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.opentok.udfs.Ved.VedMessage.Mysterious result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.opentok.udfs.Ved.VedMessage.Mysterious buildPartial() {
          com.opentok.udfs.Ved.VedMessage.Mysterious result = new com.opentok.udfs.Ved.VedMessage.Mysterious(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (nestedMysteriousMsgBuilder_ == null) {
            result.nestedMysteriousMsg_ = nestedMysteriousMsg_;
          } else {
            result.nestedMysteriousMsg_ = nestedMysteriousMsgBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.opentok.udfs.Ved.VedMessage.Mysterious) {
            return mergeFrom((com.opentok.udfs.Ved.VedMessage.Mysterious)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.opentok.udfs.Ved.VedMessage.Mysterious other) {
          if (other == com.opentok.udfs.Ved.VedMessage.Mysterious.getDefaultInstance()) return this;
          if (other.hasNestedMysteriousMsg()) {
            mergeNestedMysteriousMsg(other.getNestedMysteriousMsg());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.Builder subBuilder = com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.newBuilder();
                if (hasNestedMysteriousMsg()) {
                  subBuilder.mergeFrom(getNestedMysteriousMsg());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setNestedMysteriousMsg(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional .com.opentok.udfs.VedMessage.Mysterious.NestedMysterious nested_mysterious_msg = 1;
        private com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious nestedMysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious, com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.Builder, com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysteriousOrBuilder> nestedMysteriousMsgBuilder_;
        public boolean hasNestedMysteriousMsg() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious getNestedMysteriousMsg() {
          if (nestedMysteriousMsgBuilder_ == null) {
            return nestedMysteriousMsg_;
          } else {
            return nestedMysteriousMsgBuilder_.getMessage();
          }
        }
        public Builder setNestedMysteriousMsg(com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious value) {
          if (nestedMysteriousMsgBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            nestedMysteriousMsg_ = value;
            onChanged();
          } else {
            nestedMysteriousMsgBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder setNestedMysteriousMsg(
            com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.Builder builderForValue) {
          if (nestedMysteriousMsgBuilder_ == null) {
            nestedMysteriousMsg_ = builderForValue.build();
            onChanged();
          } else {
            nestedMysteriousMsgBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder mergeNestedMysteriousMsg(com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious value) {
          if (nestedMysteriousMsgBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                nestedMysteriousMsg_ != com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDefaultInstance()) {
              nestedMysteriousMsg_ =
                com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.newBuilder(nestedMysteriousMsg_).mergeFrom(value).buildPartial();
            } else {
              nestedMysteriousMsg_ = value;
            }
            onChanged();
          } else {
            nestedMysteriousMsgBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder clearNestedMysteriousMsg() {
          if (nestedMysteriousMsgBuilder_ == null) {
            nestedMysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.getDefaultInstance();
            onChanged();
          } else {
            nestedMysteriousMsgBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.Builder getNestedMysteriousMsgBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getNestedMysteriousMsgFieldBuilder().getBuilder();
        }
        public com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysteriousOrBuilder getNestedMysteriousMsgOrBuilder() {
          if (nestedMysteriousMsgBuilder_ != null) {
            return nestedMysteriousMsgBuilder_.getMessageOrBuilder();
          } else {
            return nestedMysteriousMsg_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious, com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.Builder, com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysteriousOrBuilder> 
            getNestedMysteriousMsgFieldBuilder() {
          if (nestedMysteriousMsgBuilder_ == null) {
            nestedMysteriousMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious, com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.Builder, com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysteriousOrBuilder>(
                    nestedMysteriousMsg_,
                    getParentForChildren(),
                    isClean());
            nestedMysteriousMsg_ = null;
          }
          return nestedMysteriousMsgBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:com.opentok.udfs.VedMessage.Mysterious)
      }
      
      static {
        defaultInstance = new Mysterious(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.opentok.udfs.VedMessage.Mysterious)
    }
    
    private int bitField0_;
    // optional uint64 link_index = 1;
    public static final int LINK_INDEX_FIELD_NUMBER = 1;
    private long linkIndex_;
    public boolean hasLinkIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getLinkIndex() {
      return linkIndex_;
    }
    
    // optional .com.opentok.udfs.VedMessage.Type link_type = 2;
    public static final int LINK_TYPE_FIELD_NUMBER = 2;
    private com.opentok.udfs.Ved.VedMessage.Type linkType_;
    public boolean hasLinkType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.opentok.udfs.Ved.VedMessage.Type getLinkType() {
      return linkType_;
    }
    
    // optional uint64 sub_result_position = 5;
    public static final int SUB_RESULT_POSITION_FIELD_NUMBER = 5;
    private long subResultPosition_;
    public boolean hasSubResultPosition() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getSubResultPosition() {
      return subResultPosition_;
    }
    
    // optional uint64 result_position = 6;
    public static final int RESULT_POSITION_FIELD_NUMBER = 6;
    private long resultPosition_;
    public boolean hasResultPosition() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getResultPosition() {
      return resultPosition_;
    }
    
    // optional uint64 start_result_position = 7;
    public static final int START_RESULT_POSITION_FIELD_NUMBER = 7;
    private long startResultPosition_;
    public boolean hasStartResultPosition() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getStartResultPosition() {
      return startResultPosition_;
    }
    
    // optional uint64 v3 = 3;
    public static final int V3_FIELD_NUMBER = 3;
    private long v3_;
    public boolean hasV3() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getV3() {
      return v3_;
    }
    
    // optional uint64 v4 = 4;
    public static final int V4_FIELD_NUMBER = 4;
    private long v4_;
    public boolean hasV4() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getV4() {
      return v4_;
    }
    
    // optional uint64 v8 = 8;
    public static final int V8_FIELD_NUMBER = 8;
    private long v8_;
    public boolean hasV8() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getV8() {
      return v8_;
    }
    
    // optional uint64 v9 = 9;
    public static final int V9_FIELD_NUMBER = 9;
    private long v9_;
    public boolean hasV9() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public long getV9() {
      return v9_;
    }
    
    // optional uint64 v10 = 10;
    public static final int V10_FIELD_NUMBER = 10;
    private long v10_;
    public boolean hasV10() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public long getV10() {
      return v10_;
    }
    
    // optional uint64 v11 = 11;
    public static final int V11_FIELD_NUMBER = 11;
    private long v11_;
    public boolean hasV11() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public long getV11() {
      return v11_;
    }
    
    // optional uint64 v12 = 12;
    public static final int V12_FIELD_NUMBER = 12;
    private long v12_;
    public boolean hasV12() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public long getV12() {
      return v12_;
    }
    
    // optional .com.opentok.udfs.VedMessage.Mysterious mysterious_msg = 13;
    public static final int MYSTERIOUS_MSG_FIELD_NUMBER = 13;
    private com.opentok.udfs.Ved.VedMessage.Mysterious mysteriousMsg_;
    public boolean hasMysteriousMsg() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public com.opentok.udfs.Ved.VedMessage.Mysterious getMysteriousMsg() {
      return mysteriousMsg_;
    }
    public com.opentok.udfs.Ved.VedMessage.MysteriousOrBuilder getMysteriousMsgOrBuilder() {
      return mysteriousMsg_;
    }
    
    private void initFields() {
      linkIndex_ = 0L;
      linkType_ = com.opentok.udfs.Ved.VedMessage.Type.normal_universal_search_result;
      subResultPosition_ = 0L;
      resultPosition_ = 0L;
      startResultPosition_ = 0L;
      v3_ = 0L;
      v4_ = 0L;
      v8_ = 0L;
      v9_ = 0L;
      v10_ = 0L;
      v11_ = 0L;
      v12_ = 0L;
      mysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, linkIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, linkType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(3, v3_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(4, v4_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(5, subResultPosition_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(6, resultPosition_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(7, startResultPosition_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(8, v8_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt64(9, v9_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt64(10, v10_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeUInt64(11, v11_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(12, v12_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeMessage(13, mysteriousMsg_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, linkIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, linkType_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, v3_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, v4_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, subResultPosition_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, resultPosition_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, startResultPosition_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, v8_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, v9_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(10, v10_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(11, v11_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, v12_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, mysteriousMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.opentok.udfs.Ved.VedMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opentok.udfs.Ved.VedMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opentok.udfs.Ved.VedMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.opentok.udfs.Ved.VedMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.opentok.udfs.Ved.VedMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opentok.udfs.Ved.VedMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.opentok.udfs.Ved.VedMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opentok.udfs.Ved.VedMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.opentok.udfs.Ved.VedMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.opentok.udfs.Ved.VedMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.opentok.udfs.Ved.VedMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.opentok.udfs.Ved.VedMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.opentok.udfs.Ved.internal_static_com_opentok_udfs_VedMessage_fieldAccessorTable;
      }
      
      // Construct using com.opentok.udfs.Ved.VedMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMysteriousMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        linkIndex_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        linkType_ = com.opentok.udfs.Ved.VedMessage.Type.normal_universal_search_result;
        bitField0_ = (bitField0_ & ~0x00000002);
        subResultPosition_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        resultPosition_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        startResultPosition_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        v3_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        v4_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        v8_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        v9_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        v10_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        v11_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        v12_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        if (mysteriousMsgBuilder_ == null) {
          mysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.getDefaultInstance();
        } else {
          mysteriousMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.opentok.udfs.Ved.VedMessage.getDescriptor();
      }
      
      public com.opentok.udfs.Ved.VedMessage getDefaultInstanceForType() {
        return com.opentok.udfs.Ved.VedMessage.getDefaultInstance();
      }
      
      public com.opentok.udfs.Ved.VedMessage build() {
        com.opentok.udfs.Ved.VedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.opentok.udfs.Ved.VedMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.opentok.udfs.Ved.VedMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.opentok.udfs.Ved.VedMessage buildPartial() {
        com.opentok.udfs.Ved.VedMessage result = new com.opentok.udfs.Ved.VedMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.linkIndex_ = linkIndex_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.linkType_ = linkType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.subResultPosition_ = subResultPosition_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.resultPosition_ = resultPosition_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.startResultPosition_ = startResultPosition_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.v3_ = v3_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.v4_ = v4_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.v8_ = v8_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.v9_ = v9_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.v10_ = v10_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.v11_ = v11_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.v12_ = v12_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        if (mysteriousMsgBuilder_ == null) {
          result.mysteriousMsg_ = mysteriousMsg_;
        } else {
          result.mysteriousMsg_ = mysteriousMsgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.opentok.udfs.Ved.VedMessage) {
          return mergeFrom((com.opentok.udfs.Ved.VedMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.opentok.udfs.Ved.VedMessage other) {
        if (other == com.opentok.udfs.Ved.VedMessage.getDefaultInstance()) return this;
        if (other.hasLinkIndex()) {
          setLinkIndex(other.getLinkIndex());
        }
        if (other.hasLinkType()) {
          setLinkType(other.getLinkType());
        }
        if (other.hasSubResultPosition()) {
          setSubResultPosition(other.getSubResultPosition());
        }
        if (other.hasResultPosition()) {
          setResultPosition(other.getResultPosition());
        }
        if (other.hasStartResultPosition()) {
          setStartResultPosition(other.getStartResultPosition());
        }
        if (other.hasV3()) {
          setV3(other.getV3());
        }
        if (other.hasV4()) {
          setV4(other.getV4());
        }
        if (other.hasV8()) {
          setV8(other.getV8());
        }
        if (other.hasV9()) {
          setV9(other.getV9());
        }
        if (other.hasV10()) {
          setV10(other.getV10());
        }
        if (other.hasV11()) {
          setV11(other.getV11());
        }
        if (other.hasV12()) {
          setV12(other.getV12());
        }
        if (other.hasMysteriousMsg()) {
          mergeMysteriousMsg(other.getMysteriousMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              linkIndex_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.opentok.udfs.Ved.VedMessage.Type value = com.opentok.udfs.Ved.VedMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                linkType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000020;
              v3_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000040;
              v4_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              subResultPosition_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              resultPosition_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              startResultPosition_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              v8_ = input.readUInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              v9_ = input.readUInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              v10_ = input.readUInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              v11_ = input.readUInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              v12_ = input.readUInt64();
              break;
            }
            case 106: {
              com.opentok.udfs.Ved.VedMessage.Mysterious.Builder subBuilder = com.opentok.udfs.Ved.VedMessage.Mysterious.newBuilder();
              if (hasMysteriousMsg()) {
                subBuilder.mergeFrom(getMysteriousMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMysteriousMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 link_index = 1;
      private long linkIndex_ ;
      public boolean hasLinkIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getLinkIndex() {
        return linkIndex_;
      }
      public Builder setLinkIndex(long value) {
        bitField0_ |= 0x00000001;
        linkIndex_ = value;
        onChanged();
        return this;
      }
      public Builder clearLinkIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        linkIndex_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .com.opentok.udfs.VedMessage.Type link_type = 2;
      private com.opentok.udfs.Ved.VedMessage.Type linkType_ = com.opentok.udfs.Ved.VedMessage.Type.normal_universal_search_result;
      public boolean hasLinkType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.opentok.udfs.Ved.VedMessage.Type getLinkType() {
        return linkType_;
      }
      public Builder setLinkType(com.opentok.udfs.Ved.VedMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        linkType_ = value;
        onChanged();
        return this;
      }
      public Builder clearLinkType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        linkType_ = com.opentok.udfs.Ved.VedMessage.Type.normal_universal_search_result;
        onChanged();
        return this;
      }
      
      // optional uint64 sub_result_position = 5;
      private long subResultPosition_ ;
      public boolean hasSubResultPosition() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getSubResultPosition() {
        return subResultPosition_;
      }
      public Builder setSubResultPosition(long value) {
        bitField0_ |= 0x00000004;
        subResultPosition_ = value;
        onChanged();
        return this;
      }
      public Builder clearSubResultPosition() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subResultPosition_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 result_position = 6;
      private long resultPosition_ ;
      public boolean hasResultPosition() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getResultPosition() {
        return resultPosition_;
      }
      public Builder setResultPosition(long value) {
        bitField0_ |= 0x00000008;
        resultPosition_ = value;
        onChanged();
        return this;
      }
      public Builder clearResultPosition() {
        bitField0_ = (bitField0_ & ~0x00000008);
        resultPosition_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 start_result_position = 7;
      private long startResultPosition_ ;
      public boolean hasStartResultPosition() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getStartResultPosition() {
        return startResultPosition_;
      }
      public Builder setStartResultPosition(long value) {
        bitField0_ |= 0x00000010;
        startResultPosition_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartResultPosition() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startResultPosition_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 v3 = 3;
      private long v3_ ;
      public boolean hasV3() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getV3() {
        return v3_;
      }
      public Builder setV3(long value) {
        bitField0_ |= 0x00000020;
        v3_ = value;
        onChanged();
        return this;
      }
      public Builder clearV3() {
        bitField0_ = (bitField0_ & ~0x00000020);
        v3_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 v4 = 4;
      private long v4_ ;
      public boolean hasV4() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getV4() {
        return v4_;
      }
      public Builder setV4(long value) {
        bitField0_ |= 0x00000040;
        v4_ = value;
        onChanged();
        return this;
      }
      public Builder clearV4() {
        bitField0_ = (bitField0_ & ~0x00000040);
        v4_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 v8 = 8;
      private long v8_ ;
      public boolean hasV8() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getV8() {
        return v8_;
      }
      public Builder setV8(long value) {
        bitField0_ |= 0x00000080;
        v8_ = value;
        onChanged();
        return this;
      }
      public Builder clearV8() {
        bitField0_ = (bitField0_ & ~0x00000080);
        v8_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 v9 = 9;
      private long v9_ ;
      public boolean hasV9() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public long getV9() {
        return v9_;
      }
      public Builder setV9(long value) {
        bitField0_ |= 0x00000100;
        v9_ = value;
        onChanged();
        return this;
      }
      public Builder clearV9() {
        bitField0_ = (bitField0_ & ~0x00000100);
        v9_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 v10 = 10;
      private long v10_ ;
      public boolean hasV10() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public long getV10() {
        return v10_;
      }
      public Builder setV10(long value) {
        bitField0_ |= 0x00000200;
        v10_ = value;
        onChanged();
        return this;
      }
      public Builder clearV10() {
        bitField0_ = (bitField0_ & ~0x00000200);
        v10_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 v11 = 11;
      private long v11_ ;
      public boolean hasV11() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public long getV11() {
        return v11_;
      }
      public Builder setV11(long value) {
        bitField0_ |= 0x00000400;
        v11_ = value;
        onChanged();
        return this;
      }
      public Builder clearV11() {
        bitField0_ = (bitField0_ & ~0x00000400);
        v11_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 v12 = 12;
      private long v12_ ;
      public boolean hasV12() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public long getV12() {
        return v12_;
      }
      public Builder setV12(long value) {
        bitField0_ |= 0x00000800;
        v12_ = value;
        onChanged();
        return this;
      }
      public Builder clearV12() {
        bitField0_ = (bitField0_ & ~0x00000800);
        v12_ = 0L;
        onChanged();
        return this;
      }
      
      // optional .com.opentok.udfs.VedMessage.Mysterious mysterious_msg = 13;
      private com.opentok.udfs.Ved.VedMessage.Mysterious mysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.opentok.udfs.Ved.VedMessage.Mysterious, com.opentok.udfs.Ved.VedMessage.Mysterious.Builder, com.opentok.udfs.Ved.VedMessage.MysteriousOrBuilder> mysteriousMsgBuilder_;
      public boolean hasMysteriousMsg() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public com.opentok.udfs.Ved.VedMessage.Mysterious getMysteriousMsg() {
        if (mysteriousMsgBuilder_ == null) {
          return mysteriousMsg_;
        } else {
          return mysteriousMsgBuilder_.getMessage();
        }
      }
      public Builder setMysteriousMsg(com.opentok.udfs.Ved.VedMessage.Mysterious value) {
        if (mysteriousMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mysteriousMsg_ = value;
          onChanged();
        } else {
          mysteriousMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      public Builder setMysteriousMsg(
          com.opentok.udfs.Ved.VedMessage.Mysterious.Builder builderForValue) {
        if (mysteriousMsgBuilder_ == null) {
          mysteriousMsg_ = builderForValue.build();
          onChanged();
        } else {
          mysteriousMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      public Builder mergeMysteriousMsg(com.opentok.udfs.Ved.VedMessage.Mysterious value) {
        if (mysteriousMsgBuilder_ == null) {
          if (((bitField0_ & 0x00001000) == 0x00001000) &&
              mysteriousMsg_ != com.opentok.udfs.Ved.VedMessage.Mysterious.getDefaultInstance()) {
            mysteriousMsg_ =
              com.opentok.udfs.Ved.VedMessage.Mysterious.newBuilder(mysteriousMsg_).mergeFrom(value).buildPartial();
          } else {
            mysteriousMsg_ = value;
          }
          onChanged();
        } else {
          mysteriousMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00001000;
        return this;
      }
      public Builder clearMysteriousMsg() {
        if (mysteriousMsgBuilder_ == null) {
          mysteriousMsg_ = com.opentok.udfs.Ved.VedMessage.Mysterious.getDefaultInstance();
          onChanged();
        } else {
          mysteriousMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      public com.opentok.udfs.Ved.VedMessage.Mysterious.Builder getMysteriousMsgBuilder() {
        bitField0_ |= 0x00001000;
        onChanged();
        return getMysteriousMsgFieldBuilder().getBuilder();
      }
      public com.opentok.udfs.Ved.VedMessage.MysteriousOrBuilder getMysteriousMsgOrBuilder() {
        if (mysteriousMsgBuilder_ != null) {
          return mysteriousMsgBuilder_.getMessageOrBuilder();
        } else {
          return mysteriousMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.opentok.udfs.Ved.VedMessage.Mysterious, com.opentok.udfs.Ved.VedMessage.Mysterious.Builder, com.opentok.udfs.Ved.VedMessage.MysteriousOrBuilder> 
          getMysteriousMsgFieldBuilder() {
        if (mysteriousMsgBuilder_ == null) {
          mysteriousMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.opentok.udfs.Ved.VedMessage.Mysterious, com.opentok.udfs.Ved.VedMessage.Mysterious.Builder, com.opentok.udfs.Ved.VedMessage.MysteriousOrBuilder>(
                  mysteriousMsg_,
                  getParentForChildren(),
                  isClean());
          mysteriousMsg_ = null;
        }
        return mysteriousMsgBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.opentok.udfs.VedMessage)
    }
    
    static {
      defaultInstance = new VedMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.opentok.udfs.VedMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_opentok_udfs_VedMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_opentok_udfs_VedMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_opentok_udfs_VedMessage_Mysterious_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_opentok_udfs_VedMessage_Mysterious_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/resources/ved.proto\022\020com.open" +
      "tok.udfs\"\210\021\n\nVedMessage\022\022\n\nlink_index\030\001 " +
      "\001(\004\0224\n\tlink_type\030\002 \001(\0162!.com.opentok.udf" +
      "s.VedMessage.Type\022\033\n\023sub_result_position" +
      "\030\005 \001(\004\022\027\n\017result_position\030\006 \001(\004\022\035\n\025start" +
      "_result_position\030\007 \001(\004\022\n\n\002v3\030\003 \001(\004\022\n\n\002v4" +
      "\030\004 \001(\004\022\n\n\002v8\030\010 \001(\004\022\n\n\002v9\030\t \001(\004\022\013\n\003v10\030\n " +
      "\001(\004\022\013\n\003v11\030\013 \001(\004\022\013\n\003v12\030\014 \001(\004\022?\n\016mysteri" +
      "ous_msg\030\r \001(\0132\'.com.opentok.udfs.VedMess" +
      "age.Mysterious\032\257\001\n\nMysterious\022W\n\025nested_",
      "mysterious_msg\030\001 \001(\01328.com.opentok.udfs." +
      "VedMessage.Mysterious.NestedMysterious\032H" +
      "\n\020NestedMysterious\022\n\n\002ts\030\001 \001(\003\022\023\n\013myster" +
      "ious1\030\002 \001(\017\022\023\n\013mysterious2\030\003 \001(\017\"\220\r\n\004Typ" +
      "e\022\"\n\036normal_universal_search_result\020\026\022\027\n" +
      "\022blog_search_result\020\230\001\022\022\n\rpatent_result\020" +
      "\350\001\022\034\n\027patent_result_thumbnail\020\353\001\022?\n:imag" +
      "e_search_result_in_basic_image_search_un" +
      "iversal_search\020\365\001\022\030\n\023local_search_result" +
      "\020\240\002\022\032\n\025news_result_thumbnail\020\247\002\022\020\n\013news_",
      "result\020\251\002\0224\n/more_results_link_listed_ma" +
      "inly_for_QA_websites\020\254\002\022\021\n\014video_result\020" +
      "\267\002\022\033\n\026video_result_thumbnail\020\270\002\022\025\n\020oneli" +
      "ne_sitelink\020\322\002\022\033\n\026shopping_search_result" +
      "\020\363\002\022\030\n\023image_search_result\020\255\003\022\033\n\027new_ima" +
      "ge_search_result\0203\022\021\n\014Jump_to_link\020\312\004\022#\n" +
      "\036map_search_result_website_link\020\344\004\022 \n\033ma" +
      "p_search_result_thumbnail\020\206\005\022\024\n\017adword_s" +
      "itelink\020\302\005\022\017\n\nbreadcrumb\020\351\005\0220\n+patent_re" +
      "sult_Overview_Related_Discuss_link\020\323\010\022#\n",
      "\036book_search_result_author_link\020\364\010\022\036\n\031no" +
      "rmal_result_thumbnail_1\020\372\010\022\036\n\031normal_res" +
      "ult_thumbnail_2\020\376\010\022(\n#local_search_resul" +
      "t_marker_pin_icon\020\257\013\022\024\n\017news_sub_result\020" +
      "\374\013\022\034\n\027sponsored_search_result\020\321\014\022\026\n\021map_" +
      "search_result\020\245\r\022&\n!knowledge_graph_repe" +
      "ated_sub_link\020\304\r\022(\n#sponsored_shopping_r" +
      "esult_thumbnail\020\363\016\022\036\n\031sponsored_shopping" +
      "_result\020\364\016\022)\n$sponsored_shopping_result_" +
      "thumbnail_\020\302\017\022>\n9sponsored_shopping_resu",
      "lt_main_column_of_universal_search\020\303\017\022\r\n" +
      "\010sitelink\020\214\020\022 \n\033news_result_video_thumbn" +
      "ail\020\275\021\022\031\n\024knowledge_graph_link\020\233\023\022\036\n\031aut" +
      "horship_by_author_link\020\237\026\022\036\n\031authorship_" +
      "thumbnail_link\020\371\026\022\"\n\035image_search_result" +
      "_thumbnail\020\204\034\0220\n+image_search_result_pre" +
      "view_View_image_link\020\214\034\022*\n%image_search_" +
      "result_preview_thumbnail\020\215\034\022+\n&image_sea" +
      "rch_result_preview_title_link\020\216\034\0220\n+imag" +
      "e_search_result_preview_Visit_page_link\020",
      "\217\034\022C\n>image_search_result_preview_grey_w" +
      "ebsite_link_underneath_title\020\214\035\022\037\n\032knowl" +
      "edge_graph_main_image\020\374\035\022\033\n\026indepth_arti" +
      "cle_result\020\325\'\022%\n indepth_article_result_" +
      "thumbnail\020\326\'\022\034\n\027adword_oneline_sitelink\020" +
      "\246(\022\037\n\032dictionary_definition_link\020\371*B\027\n\020c" +
      "om.opentok.udfsB\003Ved"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_opentok_udfs_VedMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_opentok_udfs_VedMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_opentok_udfs_VedMessage_descriptor,
              new java.lang.String[] { "LinkIndex", "LinkType", "SubResultPosition", "ResultPosition", "StartResultPosition", "V3", "V4", "V8", "V9", "V10", "V11", "V12", "MysteriousMsg", },
              com.opentok.udfs.Ved.VedMessage.class,
              com.opentok.udfs.Ved.VedMessage.Builder.class);
          internal_static_com_opentok_udfs_VedMessage_Mysterious_descriptor =
            internal_static_com_opentok_udfs_VedMessage_descriptor.getNestedTypes().get(0);
          internal_static_com_opentok_udfs_VedMessage_Mysterious_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_opentok_udfs_VedMessage_Mysterious_descriptor,
              new java.lang.String[] { "NestedMysteriousMsg", },
              com.opentok.udfs.Ved.VedMessage.Mysterious.class,
              com.opentok.udfs.Ved.VedMessage.Mysterious.Builder.class);
          internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_descriptor =
            internal_static_com_opentok_udfs_VedMessage_Mysterious_descriptor.getNestedTypes().get(0);
          internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_opentok_udfs_VedMessage_Mysterious_NestedMysterious_descriptor,
              new java.lang.String[] { "Ts", "Mysterious1", "Mysterious2", },
              com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.class,
              com.opentok.udfs.Ved.VedMessage.Mysterious.NestedMysterious.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
